services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Rome'
    # Volumes store your data between container upgrades
    volumes:
      - '${APP_DATA_DIR}/db:/var/www/html/db'
      - '${APP_DATA_DIR}/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped

