services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:v2.27.3
    ports:
      - "11447:80/tcp"
    environment:
      TZ: 'Europe/Rome'
    # Volumes store your data between container upgrades
    volumes:
      - '${APP_DATA_DIR}/db:/var/www/html/db'
      - '${APP_DATA_DIR}/logos:/var/www/html/images/uploads/logos'
    restart: on-failure

