version: "3.8"

services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    ports:
      - "11444:80"
    volumes:
      - ${APP_DATA_DIR}/app_images:/var/www/html/public/img
      - ${APP_DATA_DIR}/app_logs:/var/www/html/app/logs
      - ${APP_DATA_DIR}/app_backup:/var/www/html/public/backup
      - ${APP_DATA_DIR}/app_themes:/var/www/html/public/themes
      - ${APP_DATA_DIR}/app_migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: "admin@example.com"
      APP_ADMIN_PASSWORD: "$APP_PASSWORD"
      APP_TIMEZONE: "Europe/Rome"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: hortusfox
      DB_PASSWORD: $APP_PASSWORD
      DB_CHARSET: "utf8mb4"
    depends_on:
      - db

  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: $APP_PASSWORD
      MYSQL_DATABASE: hortusfox
      MYSQL_USER: hortusfox
      MYSQL_PASSWORD: $APP_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ${APP_DATA_DIR}/db_data:/var/lib/mysql

volumes:
  db_data:
  app_images:
  app_logs:
  app_backup:
  app_themes:
  app_migrate: