services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:v1.18.1
    restart: on-failure
    ports:
      # Host Port:Container Port
      - 11448:8080
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - WT_JWT_ENCRYPTION_KEY=${APP_SEED}

