services:
  tubearchivist:
    container_name: tubearchivist
    restart: on-failure
    image: bbilly1/tubearchivist:v0.4.10
    ports:
      - 11444:8000
    volumes:
      - ${APP_DATA_DIR}/media:/youtube
      - ${APP_DATA_DIR}/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port http://archivist-es:9200
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=$DEVICE_DOMAIN_NAME         # set your host name - can have multiple, just separate with space
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=$APP_PASSWORD           # your initial TA credentials
      - ELASTIC_PASSWORD=$APP_PASSWORD      # set password for Elasticsearch
      - TZ=Europe/Rome                      # set your time zone (eg. America/New_York)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.100:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: on-failure
    expose:
      - "6379"
    volumes:
      - ${APP_DATA_DIR}/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es:latest        # only for amd64, or use official es 8.13.2
    container_name: archivist-es
    restart: on-failure
    environment:
      - "ELASTIC_PASSWORD=$APP_PASSWORD"           # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${APP_DATA_DIR}/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
