services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:v24.05.4
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - APP_URL=$DEVICE_DOMAIN_NAME
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=$APP_PASSWORD
      - DB_DATABASE=bookstackapp
    volumes:
      - ${APP_DATA_DIR}/app_data:/config
    ports:
      - 6875:80
    restart: on-failure
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - MYSQL_ROOT_PASSWORD=$APP_PASSWORD
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=$APP_PASSWORD
    volumes:
      - ${APP_DATA_DIR}/db_data:/config
    restart: on-failure