---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      #- APP_URL=
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=LDdQSapSK3gpFUFQ%XcThEg9GU8*HHjouJ3p
      - DB_DATABASE=bookstackapp
    volumes:
      - ${APP_DATA_DIR}/app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - MYSQL_ROOT_PASSWORD=LDdQSapSK3gpFUFQ%XcThEg9GU8*HHjouJ3p
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=LDdQSapSK3gpFUFQ%XcThEg9GU8*HHjouJ3p
    volumes:
      - ${APP_DATA_DIR}/db_data:/config
    restart: unless-stopped