version: '3'
services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    ports:
      - '11436:8080'
    environment:
      PICSUR_HOST: $DEVICE_DOMAIN_NAME
      # PICSUR_PORT: 8080

      PICSUR_DB_HOST: picsur_postgres
      PICSUR_DB_PORT: 5432
      PICSUR_DB_USERNAME: picsur
      PICSUR_DB_PASSWORD: $APP_PASSWORD
      PICSUR_DB_DATABASE: picsur

      ## The default username is admin, this is not modifyable
      PICSUR_ADMIN_PASSWORD: $APP_PASSWOR

      ## Optional, random secret will be generated if not set
      PICSUR_JWT_SECRET: $APP_SEED
      # PICSUR_JWT_EXPIRY: 7d

      ## Maximum accepted size for uploads in bytes
      # PICSUR_MAX_FILE_SIZE: 128000000
      ## No need to touch this, unless you use a custom frontend
      # PICSUR_STATIC_FRONTEND_ROOT: "/picsur/frontend/dist"

      ## Warning: Verbose mode might log sensitive data
      # PICSUR_VERBOSE: "true"
    restart: on-failure
  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    environment:
      POSTGRES_DB: picsur
      POSTGRES_PASSWORD: $APP_PASSWORD
      POSTGRES_USER: picsur
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/picsur-data:/var/lib/postgresql/data
volumes:
  picsur-data: