services:
  app:
    image: monica:apache
    depends_on:
      - db
    ports:
      - 10020:80
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=monica
      - DB_USERNAME=monica
      - DB_PASSWORD=LDdQSapSK3gpFUFQ%XcThEg9GU8*HHjouJ3p
      - LOG_CHANNEL=stderr
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_DRIVER=sync
      # The encryption key. This is the most important part of the application. Keep
      # this secure otherwise, everyone will be able to access your application.  
      # Must be 32 characters long exactly.
      # Use `php artisan key:generate` or `echo -n 'base64:'; openssl rand -base64 32` to generate a random key.
      #- APP_KEY=59104484544155400163028902188121
            

      # true if you want to show debug information on errors. For production, put this
      # to false.

      # Prevent information leakage by referring to IDs with hashIds instead of
      # the actual IDs used in the database.
      - HASH_SALT=hhu0ftTGur97gn1V0mhV
      - HASH_LENGTH=18

      # The URL of your application.
      - APP_URL=$DEVICE_DOMAIN_NAME

      # Force using APP_URL as base url of your application.
      # You should not need this, unless you are using subdirectory config.
      - APP_FORCE_URL=false

      # Database information
      # To keep this information secure, we urge you to change the default password
      # Currently only "mysql" compatible servers are working
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306

      # Use utf8mb4 database charset format to support emoji characters
      # ⚠ be sure your DBMS supports utf8mb4 format
      - DB_USE_UTF8MB4=true

      # Ability to disable signups on your instance.
      # Can be true or false. Default to false.
      - APP_DISABLE_SIGNUP=true

      # Enable user email verification.
      - APP_SIGNUP_DOUBLE_OPTIN=false

      # Set trusted proxy IP addresses.
      # To trust all proxies that connect directly to your server, use a "*".
      # To trust one or more specific proxies that connect directly to your server,
      # use a comma separated list of IP addresses.
      - APP_TRUSTED_PROXIES=

      # Enable automatic cloudflare trusted proxy discover
      - APP_TRUSTED_CLOUDFLARE=false

      - LOG_CHANNEL=daily
      - SENTRY_SUPPORT=false


      # Send a daily ping to https://version.monicahq.com to check if a new version
      # is available. When a new version is detected, you will have a message in the
      # UI, as well as the release notes for the new changes. Can be true or false.
      # Default to true.
      - CHECK_VERSION=true

      # Cache, session, and queue parameters
      # ⚠ Change this only if you know what you are doing
      #. Cache: database, file, memcached, redis, dynamodb
      #. Session: file, cookie, database, apc, memcached, redis, array
      #. Queue: sync, database, beanstalkd, sqs, redis
      #  If Queue is not set to 'sync', you'll have to set a queue worker
      #  See https://laravel.com/docs/5.7/queues#running-the-queue-worker
      - CACHE_DRIVER=database
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - QUEUE_CONNECTION=sync
      # Maximum allowed size for uploaded files, in kilobytes.
      # Make sure this is an integer, without commas or spaces.
      - DEFAULT_MAX_UPLOAD_SIZE=10240

      # Maximum allowed storage size per account, in megabytes.
      # Make sure this is an integer, without commas or spaces.
      - DEFAULT_MAX_STORAGE_SIZE=512
      - FILESYSTEM_DISK=public
      # Enable DAV support
      - DAV_ENABLED=true
      # CLIENT ID and SECRET used for OAuth authentication
      - PASSPORT_PASSWORD_GRANT_CLIENT_ID=
      - PASSPORT_PASSWORD_GRANT_CLIENT_SECRET=

      - ALLOW_STATISTICS_THROUGH_PUBLIC_API_ACCESS=false
      - POLICY_COMPLIANT=true
      - ENABLE_GEOLOCATION=false
      - ENABLE_WEATHER=false

      # Configure rate limits for RouteService per minute
      - RATE_LIMIT_PER_MINUTE_API=60
      - RATE_LIMIT_PER_MINUTE_OAUTH=5
    volumes:
      - ./data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=LDdQSapSK3gpFUFQ%XcThEg9GU8*HHjouJ3p
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
