services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: on-failure
    environment:
      - PUBLIC_SERVER_URL=http://server:11442 # MOST DOCKER USERS WILL NEVER NEED TO CHANGE THIS, EVEN IF YOU CHANGE THE PORTS
      - ORIGIN=http://localhost:11441
      - BODY_SIZE_LIMIT=Infinity # This is measured in bytes
    ports:
      - "11441:3000"
    depends_on:
      - server

  db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    restart: on-failure
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: $APP_PASSWORD
    volumes:
      - ${APP_DATA_DIR}/postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: on-failure
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=$APP_PASSWORD # This should be the same as the POSTGRES_PASSWORD in the db service
      - SECRET_KEY=$APP_SEED
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://localhost:81' # NOTE: THIS IS THE PUBLIC URL TO THE **NGINX** SERVER USED FOR MEDIA FILES!
      - CSRF_TRUSTED_ORIGINS=https://api.adventurelog.app,https://adventurelog.app # This is a comma separated list of trusted origins for CSRF, this should include where your frontend is hosted.
      - DEBUG=False
      - FRONTEND_URL='http://localhost:11441' # This is the URL of the frontend server
      #- DISABLE_REGISTRATION=True
    ports:
      - "11442:8000"
    depends_on:
      - db
    volumes:
      - ${APP_DATA_DIR}/adventurelog_media:/code/media/

  nginx:
    image: nginx:latest
    container_name: adventurelog-nginx
    restart: on-failure
    ports:
      - "81:80"
    volumes:
      - ${APP_DATA_DIR}/adventurelog_media:/app/media
      - ${APP_DATA_DIR}/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

volumes:
  postgres_data:
  adventurelog_media: