services:
  dash:
    image: mauricenino/dashdot:latest
    restart: on-failure
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    ports:
      - '11438:3001'
    volumes:
      - ${APP_DATA_DIR}/:/mnt/host:ro