version: '2.1'
services:
  hammond:
    image: alfhou/hammond
    container_name: hammond
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/assets
    ports:
      - 11440:3000
    restart: on-failure