version: "3"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jwilder/nginx-proxy:alpine'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      - DEFAULT_HOST=${HOST}
      - HSTS=off
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  
  proxy-letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    restart: always
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  
  send:
    image: 'registry.gitlab.com/timvisee/send:latest'
    restart: always
    ports:
      - '1234:1234'
    volumes:
      - ${APP_DATA_DIR}/uploads:/uploads
    environment:
      - VIRTUAL_HOST=send.example.org
      - VIRTUAL_PORT=1234
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - BASE_URL=https://send.example.or
      - PORT=1234
      - REDIS_HOST=redis
      - FILE_DIR=${APP_DATA_DIR}/uploads
      # To customize upload limits
      # - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000,31536000
      # - DEFAULT_EXPIRE_SECONDS=3600
      # - MAX_EXPIRE_SECONDS=31536000
      # - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000
      # - MAX_DOWNLOADS=1000
      # - MAX_FILE_SIZE=2684354560





  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - send-redis:/data

volumes:
  send-redis:
  proxy-certs:
  proxy-vhost:
  proxy-html: