version: "3.3"
services:
  flightlog:
    ports:
      - 11435:8080
    image: perdian/flightlog:v2.1.1
    environment:
      - FLIGHTLOG_SERVER_CONTEXT_PATH=/
      - FLIGHTLOG_SERVER_PORT=11435
    restart: on-failure
networks: {}
